### ISSUE TITLE
Setting the data path

### ISSUE THREAD

**Issue by thom966** [hanouticelina/deformable-DETR#4]
Hello, thank you for your work and I am trying to train the coco dataset with the provided code.
I have organized the coco dataset as follows:

```
deformable-DETR
     datasets
          tempory
               coco
                    images
                         train2017
```

However, when I run the training code, it gives me an error: `FileNotFoundError: [Errno 2] No such file or directory: '/tempory/coco/images/train2017/000000341198.jpg' ` although the image file is located in the folder.
How to resolve this issue?

Thank you for your help.

**Comment by hanouticelina** [comment]
Hello,
It depends on where you're running your script. if you are in `deformable-DETR` folder, you should specify `datasets/tempory/coco/images` as the data folder.
